#!/usr/bin/env python3
"""Render example-milestones/milestones.json into example-milestones/index.html.

The page must be readable with JavaScript disabled, so the accordion (the
small-screen form of the same five milestones per domain) is rendered here at
build time. milestones.js reads the same data from the <script type="application/json">
block this script also writes, and progressively enhances the accordion into a
date-positioned horizontal rail when the container is wide enough. There is one
content source: milestones.json. Never hand-edit the generated block.

Usage:
    python build-milestones.py            rewrite the generated block
    python build-milestones.py --check    exit 1 if the block is out of date
"""
import html
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "example-milestones", "milestones.json")
PAGE = os.path.join(HERE, "example-milestones", "index.html")

BEGIN = "<!-- BEGIN generated by build-milestones.py - do not edit by hand -->"
END = "<!-- END generated by build-milestones.py -->"

for _s in (sys.stdout, sys.stderr):
    try:
        _s.reconfigure(encoding="utf-8", errors="replace")
    except (AttributeError, ValueError):
        pass


def pair(tag, en, zh, cls=""):
    """An en/zh twin pair of block elements, per the site's i18n convention."""
    c = ' class="%s"' % cls if cls else ""
    return ('<{t}{c} lang="en">{en}</{t}>\n<{t}{c} lang="zh">{zh}</{t}>'
            .format(t=tag, c=c, en=en, zh=zh))


def span_pair(en, zh):
    """An en/zh twin pair of spans, for labels that must stay one element."""
    return '<span lang="en">%s</span><span lang="zh">%s</span>' % (en, zh)


def sources(ev, indent):
    pad = " " * indent
    if not ev.get("s"):
        return (pad + '<p class="tl-sources tl-pending">'
                + span_pair("Source pending", "来源待补") + "</p>")
    links = []
    for name, url in ev["s"]:
        links.append('<a href="%s" target="_blank" rel="noopener">%s</a>'
                     % (html.escape(url, quote=True), html.escape(name)))
    return (pad + '<p class="tl-sources"><span class="tl-sources-label">'
            + span_pair("Sources", "来源") + "</span> " + " ".join(links) + "</p>")


def milestone_body(d, ev, i, indent):
    """Finding, context, grade tag and sources. Shared by accordion and (via
    the JSON block) the rail's detail panel, so the two never diverge."""
    pad = " " * indent
    g = ev["g"]
    grade = GRADES[g]
    if ev.get("placeholder"):
        tag_en = "PLACEHOLDER &mdash; not for publication"
        tag_zh = "占位内容 &mdash; 不可发布"
        tag_class = "tl-grade tl-grade-placeholder"
        why_en = ev.get("why", "")
        why_zh = ev.get("why_zh", "")
    else:
        tag_en, tag_zh = grade["label"], grade["label_zh"]
        tag_class = "tl-grade tl-grade-" + g
        why_en, why_zh = ev.get("why", ""), ev.get("why_zh", "")
    out = [
        pad + '<p class="%s">%s</p>' % (tag_class, span_pair(tag_en, tag_zh)),
        pad + pair("p", ev["f"], ev["f_zh"], "tl-finding").replace("\n", "\n" + pad),
        pad + pair("p", ev["c"], ev["c_zh"], "tl-context").replace("\n", "\n" + pad),
        pad + pair("p", why_en, why_zh, "tl-why").replace("\n", "\n" + pad),
        sources(ev, indent),
    ]
    return "\n".join(out)


def accordion(d, indent):
    pad = " " * indent
    out = []
    for i, ev in enumerate(d["ev"]):
        bid = "acc-%s-%d" % (d["k"], i)
        out.append(pad + '<div class="tl-item">')
        out.append(pad + '  <h3 class="tl-item-h">')
        out.append(pad + '    <button type="button" class="tl-acc-btn" id="%s-btn"'
                         ' aria-expanded="false" aria-controls="%s" data-i="%d">' % (bid, bid, i))
        out.append(pad + '      <span class="tl-dot" data-grade="%s" aria-hidden="true"></span>'
                   % ("ph" if ev.get("placeholder") else ev["g"]))
        out.append(pad + '      <span class="tl-date">%s</span>'
                   % span_pair(ev["date"], ev["date_zh"]))
        out.append(pad + '      <span class="tl-item-t">%s</span>'
                   % span_pair(ev["t"], ev["t_zh"]))
        out.append(pad + '    </button>')
        out.append(pad + '  </h3>')
        out.append(pad + '  <div class="tl-acc-body" id="%s" role="region"'
                         ' aria-labelledby="%s-btn" hidden>' % (bid, bid))
        out.append(milestone_body(d, ev, i, indent + 4))
        out.append(pad + '  </div>')
        out.append(pad + '</div>')
    return "\n".join(out)


def legend(indent):
    pad = " " * indent
    out = [pad + '<div class="tl-legend">',
           pad + '  <p class="tl-legend-h">%s</p>'
           % span_pair("Evidence grade", "证据等级")]
    for key in ("ind", "dev", "obs"):
        g = GRADES[key]
        out.append(pad + '  <p class="tl-legend-item">'
                         '<span class="tl-dot" data-grade="%s" aria-hidden="true"></span>'
                         '<span class="tl-legend-label">%s</span> '
                         '<span class="tl-legend-def">%s</span></p>'
                   % (key,
                      span_pair(g["label"], g["label_zh"]),
                      span_pair(g["def"], g["def_zh"])))
    out.append(pad + '</div>')
    return "\n".join(out)


def notes(data, indent):
    pad = " " * indent
    out = [pad + '<section class="tl-notes">',
           pad + '  <h2 class="tl-notes-h">%s</h2>'
           % span_pair("Reading notes", "阅读提示")]
    for n in data["notes"]:
        out.append(pad + '  <div class="tl-note">')
        out.append(pad + '    <p class="tl-note-n">%s</p>' % n["n"])
        if n.get("t"):
            out.append(pad + '    <p class="tl-note-t">%s</p>' % span_pair(n["t"], n["t_zh"]))
        out.append(pad + '    ' + pair("p", n["b"], n["b_zh"], "tl-note-b")
                   .replace("\n", "\n" + pad + "    "))
        out.append(pad + '  </div>')
    out.append(pad + '</section>')
    return "\n".join(out)


def render(data):
    out = [BEGIN, legend(6), ""]
    for d in data["domains"]:
        k = d["k"]
        out.append('      <section class="tl-domain" data-domain="%s" style="--accent: %s;">'
                   % (k, d["accent"]))
        out.append('        <p class="tl-kicker">%s</p>' % span_pair(d["kicker"], d["kicker_zh"]))
        out.append('        <h2 class="tl-h" id="domain-%s">%s</h2>' % (k, span_pair(d["h"], d["h_zh"])))
        out.append('        ' + pair("p", d["thesis"], d["thesis_zh"], "tl-thesis")
                   .replace("\n", "\n        "))
        out.append('        <div class="tl-rail-wrap" data-rail="%s" hidden></div>' % k)
        out.append('        <p class="tl-hint" hidden>%s</p>'
                   % span_pair(data["hint"], data["hint_zh"]))
        out.append('        <div class="tl-panel" id="panel-%s" hidden></div>' % k)
        out.append('        <div class="tl-accordion" id="accordion-%s">' % k)
        out.append(accordion(d, 10))
        out.append('        </div>')
        out.append('        ' + pair("p", d["caveat"], d["caveat_zh"], "tl-caveat")
                   .replace("\n", "\n        "))
        out.append('      </section>')
        out.append("")
    out.append(notes(data, 6))
    out.append('      <p class="tl-colophon">%s</p>'
               % span_pair(data["colophon"], data["colophon_zh"]))
    payload = {k: data[k] for k in ("axis", "grades", "domains")}
    out.append('      <script type="application/json" id="tl-data">')
    out.append(json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
               .replace("</", "<\\/"))
    out.append('      </script>')
    out.append("      " + END)
    return "\n".join(out)


def main():
    with open(DATA, encoding="utf-8") as fh:
        data = json.load(fh)
    global GRADES
    GRADES = data["grades"]

    for d in data["domains"]:
        if len(d["ev"]) != 5:
            sys.exit("[milestones] domain %s has %d entries, expected 5" % (d["k"], len(d["ev"])))
        order = [(e["y"], e["mo"]) for e in d["ev"]]
        if order != sorted(order):
            sys.exit("[milestones] domain %s entries are not in chronological order" % d["k"])
        for e in d["ev"]:
            if not 1 <= e["mo"] <= 12:
                sys.exit("[milestones] domain %s has month %r" % (d["k"], e["mo"]))

    with open(PAGE, encoding="utf-8") as fh:
        page = fh.read()
    block = render(data)
    pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
    if not pattern.search(page):
        sys.exit("[milestones] markers not found in %s" % PAGE)
    new = pattern.sub(lambda _: block, page)

    if "--check" in sys.argv:
        if new != page:
            sys.exit("[milestones] index.html is out of date - run python build-milestones.py")
        print("[milestones] index.html is up to date")
        return

    if new == page:
        print("[milestones] no change")
    else:
        with open(PAGE, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(new)
        print("[milestones] wrote %s" % PAGE)

    n = sum(len(d["ev"]) for d in data["domains"])
    ph = sum(1 for d in data["domains"] for e in d["ev"] if e.get("placeholder"))
    missing = sum(1 for d in data["domains"] for e in d["ev"] if not e.get("s"))
    print("[milestones] %d milestones, %d placeholder, %d without sources" % (n, ph, missing))
    if ph or missing:
        print("[milestones] NOT READY TO PUBLISH: replace placeholders and add verified sources")


if __name__ == "__main__":
    main()
